# Generated by Django 4.2.5 on 2023-09-06 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='标题')),
                ('summary', models.CharField(blank=True, max_length=1024, null=True, verbose_name='摘要')),
                ('author', models.CharField(blank=True, max_length=64, null=True, verbose_name='作者')),
                ('post_time', models.DateTimeField(verbose_name='发布时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('cover_urls', models.CharField(blank=True, max_length=2048, null=True, verbose_name='封面')),
                ('status', models.SmallIntegerField(choices=[(0, '草稿'), (2, '已下线'), (1, '已发布'), (3, '置顶')], default=0, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
